### ISSUE TITLE
alert.partalert.net links not opening anymore

### ISSUE THREAD

**Issue by Smidelis** [Smidelis/discord-link-opener#13]
PartAlert link format has been changed. Building amazon link is not working anymore because the information has been removed from the link.

**Comment by ryanthom139** [comment]
It still doesn't open links for me

**Comment by Smidelis** [comment]
Have you downloaded the latest version? Have not had time to test it yet, was just removing the part constructing the Amazon URL.

**Comment by ryanthom139** [comment]
yeah, I have the latest version

**Comment by Smidelis** [comment]
Had it now running for two days and it's working fine so far.
