### ISSUE TITLE
Links not opening

### ISSUE THREAD

**Issue by Matsu16** [Smidelis/discord-link-opener#3]
Only the links send by myself are opening (even with the latest update).  

https://stackoverflow.com/questions/67339174/discord-api-soft-ban-for-selfbot-it-can-only-read-its-own-messages/67341709#67341709

>>

Possible solution: https://github.com/dolfies/discord.py-self 

Dont know how to make this work.

**Comment by Smidelis** [comment]
Have you had a look at Issue #2?
Myself and some of my colleagues are running it without problems as long as we provide keywords. The selfbot problem was bypassed in this script.

**Comment by Matsu16** [comment]
Ok so i noticed it works for partalert. Is there a way to make it run for a diff stock checker? what part do i need to add/ change

**Comment by Smidelis** [comment]
You need to remove the function to generate the Amazon link from the PartAlert Link:
https://github.com/Smidelis/discord-link-opener/blob/831048e5fe88c7da802abee06c41aab42aded97a/open.py#L55

And remove the related part from the `check_urls()` function:
https://github.com/Smidelis/discord-link-opener/blob/831048e5fe88c7da802abee06c41aab42aded97a/open.py#L77

No need for a condition `if else` anymore. The `else` part should be enough, like in the original skript by clearyy.

You might also need to rework the `on_message()` function, depending on how your discord server is sending the alerts.

**Comment by Matsu16** [comment]
Thanks!. This must be the on_message then.

**Comment by Matsu16** [comment]
maby u can help me with the server https://discord.com/invite/GJhk27fa 

Everything matches now, but its not opening the links. Everything is in. ID's,regex match.

**Comment by Smidelis** [comment]
Unfortunately, I don't have time for further troubleshooting at the moment.
Are you providing keywords when you run the script?

**Comment by Matsu16** [comment]
Yes, al the keywords are in. Sad it still not working for this channel. I have to give up. Maby u can look at it if you have some time.

**Comment by Smidelis** [comment]
Please try the "Generalized" branch https://github.com/Smidelis/discord-link-opener/tree/Generalized

**Comment by Matsu16** [comment]
Thank you, but i got it working already on my macbook. +pygame install voor sound on mac.

**Comment by Smidelis** [comment]
Can you share your solution?

**Comment by Matsu16** [comment]
I used the RockyLogic opener combined with the new fix (python3 -m pip install -U discord.py-self) 

*Uninstall old version first (discord.py)
*Made i mac ready with new lines to open browser
*Import Pygame to play wav.mp3 alarm sounds.
