### ISSUE TITLE
It does not open new tabs

### ISSUE THREAD

**Issue by Atoms98** [Smidelis/discord-link-opener#5]
Great program, however I ran into some problems. 

The program opens the links only when Edge is closed, if the browser is open when the notification from part alert arrives, the browser (edge) **does not open any new tab**. The only way to fix this is to manually close edge. 
The bell sound is only heard when Edge is closed after opening the Link.

**Comment by Smidelis** [comment]
I had similar problems in the beginning. The behaviour changes depending on your default browser. Try to change the path in the script to the path of your default browser and check if it works then. Apart from that try setting your default browser to Edge. Might also fix your issue.
