### ISSUE TITLE
Partalert links no longer get built correctly into amazon links

### ISSUE THREAD

**Issue by ryanthom139** [Smidelis/discord-link-opener#7]

**Comment by pedrorq** [comment]
I can confirm this, that regexp might need some adjustments

**Comment by pedrorq** [comment]
Since PartAlert url format was changed, testing following fix:

Replace the following:

    # Split url and filter needed parts
    asin, price, smid, tag, timestamp, title, tld = url.split("&")

    # For the product id and country search for the last '=' and collect the part after it
    prod_id, country = (info[info.rfind("=")+1:] for info in (asin, tld))


With:

    # Split url and filter needed parts
    asin, price, smid, tag, timestamp, title, tld, token = url.split("&")

    #Collect prod_id and country values from their respective tags after the =
    prod_id = asin.split("=",1)[1]
    country = tld.split("=",1)[1]

**Comment by pedrorq** [comment]
There's probably a better way of doing this by identifying specific URL parameters instead of expecting a given order, and then capturing everything between "tld=" and either the next "&" or EOS, but I am rusty

**Comment by sabifa** [comment]
Just in case if the order of the parameters will be switched again I would suggest you to use a more solid implementation which does not rely on the order of them.

```python
# Add the imports to the top of the file
import urllib.parse as urlparse
from urllib.parse import parse_qs

# --- updated function ---
def get_amazon_url(url):
    """
    This function collects and returns an amazon link
    that would be linked through the green button on the webpage.
    :param url: An partalert.net link for an amazon product
    :return: The extracted amazon link to the product
    """
    # Parse url to obtain query parameters
    parsed = urlparse.urlparse(url)

    country = parse_qs(parsed.query)['tld'][0]
    prod_id = parse_qs(parsed.query)['asin'][0]
    tag = parse_qs(parsed.query)['tag'][0]
    smid = parse_qs(parsed.query)['smid'][0]

    # Create full Amazon url
    url = f"https://www.amazon{country}/dp/{prod_id}?{tag}&linkCode=ogi&th=1&psc=1&{smid}"
    return url
```

Tested with the latest 3080 link from Amazon.de with an online python compiler. Use this code to try it yourself:
```python
# try this code on a site like https://www.programiz.com/python-programming/online-compiler/

import urllib.parse as urlparse
from urllib.parse import parse_qs

url = "https://partalert.net/product.js?asin=B092CYHPDJ&price=%E2%82%AC1%2C500.00&smid=A3JWKAKR8XB7XF&tag=partalertde-21&timestamp=18%3A54+UTC+%2820.5.2021%29&title=MSI+GeForce+RTX+3080+Gaming+Z+Trio+10G&tld=.de"

# Parse url to obtain query parameters
parsed = urlparse.urlparse(url)

country = parse_qs(parsed.query)['tld'][0]
prod_id = parse_qs(parsed.query)['asin'][0]
tag = parse_qs(parsed.query)['tag'][0]
smid = parse_qs(parsed.query)['smid'][0]

print(f"https://www.amazon{country}/dp/{prod_id}?{tag}&linkCode=ogi&th=1&psc=1&{smid}")
```

**Comment by Smidelis** [comment]
@sabifa, can you please open a new pull request with your changes? I think everyone would highly appreciate it :)
Thanks a lot!

**Comment by sabifa** [comment]
Done 🚀
